
output_dir: 'C:/temp/'
temp_dir: 'C:/temp/'

# Write limit order book snapshots or not
book_snapshots: True
# Period between LOB snapshots through http request
snapshot_period: 60*5
# depth limit
snapshot_limit: 100


#
# SYMBOLS CONFIGURATION REQUIREMENTS
#
# Valid spot depth steams ('spot_depth_stream'):
# - @depth - depth updates period is 1000ms
# - @depth@100ms - depth updates period is 100ms
#
# Valid futures depth steams ('spot_depth_stream'):
# - @depth - depth updates period is 250ms
# - @depth@500ms - depth updates period is 500ms
# - @depth@100ms - depth updates period is 100ms (if existing)

depth_streams: {
    spot: [
            'bnbusdt@depth@100ms',
            'btcusdt@depth@100ms',
            'ethusdt@depth@100ms',
            'ltcusdt@depth@100ms',
            'oneusdt@depth@100ms'
    ],
    futures: [
            'bnbusdt@depth@100ms',
            'btcusdt@depth@100ms',
            'ethusdt@depth@100ms',
            'ltcusdt@depth@100ms',
            'oneusdt@depth@100ms'
    ]
}

trade_streams: {
    spot: [
            'bnbusdt@trade',
            'btcusdt@trade',
            'ethusdt@trade',
            'ltcusdt@trade',
            'oneusdt@trade'
    ],
    futures: [
            'bnbusdt@trade',
            'btcusdt@trade',
            'ethusdt@trade',
            'ltcusdt@trade',
            'oneusdt@trade'
    ]
}

